#model config
model_type: "transformer"
input_size: 80
N_enc: 12
d_model: 512 #256
d_ff: 2048    
n_head: 8 #4
dropout: 0.1 
causal: False
forward: True
ctc_alpha: 1
interctc_alpha: 0
interctc_layer: 0
resume_model: ""

#conformer related conf
use_conv_enc: False
share_ff: False
d_encff: 1024
d_decff: 2048
pos_type: "relative"
enc_max_relative_len: 20
enc_kernel_size: 31

n_features: 80
vocab_size: 4990
left_ctx: 0
right_ctx: 0
skip_frame: 1

#noam warm up
warmup_type: 'noam_warmup'   # noam_warmup, custom_exp, custom_linear
noam_factor: 0.0002          # learning rate for noam_warmup, factor for custom_exp
warmup_steps: 10000 
total_steps: 100000          # for custom_linear

#cosine learning schedule
cosine_total: 100000
cosine_warmup: 1000

#Double, multistep
decay_rate: 0.01
s_warm: 2000
s_decay: 40000
s_keep: 160000

#normal
learning_rate: 0.0002
min_lr: 0.000002
patience: 2
anneal_lr_ratio: 0.5

# dataloader
dataset_type: "DynamicDataset"   #"SpeechDataset, DynamicDataset"
max_len: 5000
batch_size: 16

batch_type: "utterance"
max_frmlen: 800 
max_lablen: 150 
filter_max: 5000
filter_min: 0

padding_idx: 0
accum_grad: 2
grad_clip: 5
weight_decay: 0

use_gpu: True

use_cmvn: True
use_specaug: False
spec_aug:
  resize_mode: "PIL"         #time warp is temporarily deactivated
  max_time_warp: 0
  max_freq_width: 27
  n_freq_mask: 2
  max_time_width: 0.05
  n_time_mask: 10
  inplace: True
  replace_with_zero: False

